version: '2'
services:
  restyaboard:
    build: .
    ports:
      - 1234:80
      - 1235:443 # https
    volumes:
      #- /etc/letsencrypt/live/example.com:/cert # 1) mount existing cert folder into container

      #  - /root/restya/media:/usr/share/nginx/html/media # we probably want to keep uploaded media persisted?
      # changing to that can kill all existing data, copy data from container into some place

    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restyaboard
#      - SMTP_DOMAIN=domain
#      - SMTP_USERNAME=user
#      - SMTP_PASSWORD=pass
#      - SMTP_SERVER=server
#      - SMTP_PORT=465
      #- HTTPS=1                   # 2) enable https
      #- CERT=/cert/fullchain.pem  # 3) place & name of certificate
      #- KEY=/cert/privkey.pem     # 4) place & name of cert key
      - TZ=Etc/UTC
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restyaboard
    restart: always
    volumes:
    #  - /root/restya/pg:/var/lib/postgresql/data  # we also probably want to keep the db persisted ?
  # pgadmin:
  #   image: fenglc/pgadmin4
  #   ports:
  #     - 1235:5050
  #   environment:
  #     - DEFAULT_USER=admin
  #     - DEFAULT_PASSWORD=admin
